export const CodigoErro = {
  // Genéricos, derivados do status HTTP
  DADOS_INVALIDOS: 'DADOS_INVALIDOS',
  REQUISICAO_INVALIDA: 'REQUISICAO_INVALIDA',
  NAO_AUTENTICADO: 'NAO_AUTENTICADO',
  SEM_PERMISSAO: 'SEM_PERMISSAO',
  NAO_ENCONTRADO: 'NAO_ENCONTRADO',
  CONFLITO: 'CONFLITO',
  MUITAS_REQUISICOES: 'MUITAS_REQUISICOES',
  SERVICO_INDISPONIVEL: 'SERVICO_INDISPONIVEL',
  ERRO_INTERNO: 'ERRO_INTERNO',

  // Banco de dados (erros do Prisma)
  REGISTRO_NAO_ENCONTRADO: 'REGISTRO_NAO_ENCONTRADO',
  REGISTRO_DUPLICADO: 'REGISTRO_DUPLICADO',
  REFERENCIA_INVALIDA: 'REFERENCIA_INVALIDA',
  BANCO_INDISPONIVEL: 'BANCO_INDISPONIVEL',

  // Autenticação e usuários
  CREDENCIAIS_INVALIDAS: 'CREDENCIAIS_INVALIDAS',
  SESSAO_INVALIDA: 'SESSAO_INVALIDA',
  EMAIL_JA_CADASTRADO: 'EMAIL_JA_CADASTRADO',
  LOGIN_GOOGLE_INDISPONIVEL: 'LOGIN_GOOGLE_INDISPONIVEL',
  USUARIO_NAO_ENCONTRADO: 'USUARIO_NAO_ENCONTRADO',
  ALTERACAO_DO_PROPRIO_PERFIL: 'ALTERACAO_DO_PROPRIO_PERFIL',

  // Solicitações
  AREA_INVALIDA: 'AREA_INVALIDA',
  SOLICITACAO_NAO_ENCONTRADA: 'SOLICITACAO_NAO_ENCONTRADA',
  TRANSICAO_INVALIDA: 'TRANSICAO_INVALIDA',
  SOLICITACAO_FINALIZADA: 'SOLICITACAO_FINALIZADA',
  EXCLUSAO_NAO_PERMITIDA: 'EXCLUSAO_NAO_PERMITIDA',
  SOLICITACAO_ALTERADA: 'SOLICITACAO_ALTERADA',
} as const;

export type CodigoErro = (typeof CodigoErro)[keyof typeof CodigoErro];
